[package]
name = "tracing-otlp"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version="4.0.1" }
actix-service = "2.0.2"
opentelemetry = { version = "=0.18", default-features = false, features = [ "trace", "rt-tokio" ]}
opentelemetry-otlp = { version = "=0.11", features = ["reqwest-client", "reqwest-rustls", "http-proto", "tls"]}
rand = { version = "0.8", features = ["log"] }
tokio = { version = "1", features = ["full"] }
tonic = { version = "0.8", features = ["tls", "tls-roots"]}
tracing = "0.1"
tracing-actix-web = "0.7"
tracing-opentelemetry = "=0.18"
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }