[app]
id = "websocket"
name = "ws基础示例"
desc = "ws基础示例"
version = "1.0.0"

[fw.web_server]
port = 8089
doc_urls = [["test env", "http://localhost:8089/"]]
tls_key = """
-----BEGIN PRIVATE KEY-----
MIIJQgIBADANBgkqhkiG9w0BAQEFAASCCSwwggkoAgEAAoICAQCeZuT0jXfIbCyI
srXkPaJ6SeqOlJyokAbGL1xcuPyqFQo2KGzStG2B7vI9EX5vPA8PaNToUSUjC/92
T+Y4Swl3cEY70F8Lw6toY2eA1m01sxgeSOyFDXzgmhdr7su+cVgLrBGh8Dus8BYo
sMcx6ytahFJmD7MjjeRbDhERi6WlC5N4KqFcPKh7kd+u0X3WmbQj/Ge+mSh2xJJB
uXofMKhFBVZTyAa4Vc4pkoVqj2nCMgBGYsDkoW48flbzFTURvB6j9MCY8X338GL8
Q1o0wvB0ghEL+VZ5SlGa56VJ/1yEZSIQkbzXsTNP19RNjwA+rKvYWG7pLaNgwVd3
5KdNYa9lkrud0JdSZiTXpRU+shQZLzZQng0+ArK85L2co45mJImPChLloMZ14tfJ
lPag2yrlaHcVpWLxgBJCSqaJnDdesBZ88YIYaS0iMfEHxeJKDBlhwCGB5k21RgdR
WDWrvxWDJ+bAUuDjNN4XWix02gNhhRCWcDAiTY2HTmvOuRRze6f8yBkXxIA5YT8Q
xQM0SVUL+Wi5Sp/rIZdRiDSyHN3w519kPd9gcf/OD6/m5GeZiwPvA6RCPc3gpNfb
NSlF0qmOm+BtP6s8oBmYV2HtIyryL0O0VaVTAWGxwAfZo82nGcZ7DCg3ov29HQFR
O0UDrbJCYWTzjddfaNSOyFr39SFMyQIDAQABAoICAGzFhVU1S9qyBYa9CVA4zrig
x1OvU0Ag3rX60bbORJpapk94RPoPcd82gNtUhvjFSiYvu3voNNMzKvJIfXOMe2ys
CV6LgKjobWzaTbnYBNhKKjapptja4TSuO4UfToNw+5/QQa9s8t2XY+//LFnn/jZD
BP4Wq9GvXu7z4t6kgVOrdlGfHHzlHmD0U6CNNJdHpr7LVUY5j+K2qyQ8xFJkrDfx
KU2Q3qR4L4C2n60D3ADBKxUqPQECpVse+oAjwPRztKqrqBGeSv0V8jL94RS4BDxN
EH2jczEIyq7PgN4mX5Z+h/zOxtlqUizyrVOw7d8b3UlLuKWgdD89pN2sgwINIU5O
vEi2qQKSb96qJlT6G1s1IWznZO2fDQyZzWXySImYsGhOh16nsfTShuZa5iEB8znh
C+9QCNemjp24IiSQQlnK/0aFSU95nKyguKLhCOXTyyd4JavBD29UsbvBHgeCpNEX
vVkH+myXSZ68kpARH33DQYnAPWmvIJ1doJFicw2Nbk6gU/peN9lBsbpOynji7H2F
aho2/uxq6VKvbcj/JChCkcaFEPJPKlpHCoISnTCgorKV+hTVj9TW3fZiirllHPrd
AEpkuFleWoZq1LqyCwVa2QfUXOiq1RF7MZgClgkGtCz8RTFn7rMG2q2LAqVv8ice
f0e1nJ5bWBM8+xzQeUyxAoIBAQDSEUrg4YaQN8KFpMghF8N6w0V98HA/ufYcN78l
U5Vpst4WQu9xdV4AQaSaSJg0Y8+ddbxxiQmZPn7Mvjo6n52kd8y9/QcCnlHrOxOP
7aPjMJoloQ0q9mfXOyeAP1DlNBtg6GVWliv5CEOrFUGzqi9GfxF9mpuiUD9C9UNc
EKPnLuXEE+z6RsVkZ6nbRUDV2Dw4+vScGkXeJkBijSCCc7vvMWDqS5i7wA20/ymp
qK3upijmp9ELIsfNma8NZvxjGL2Q202WV1sROY9RmZ2Pw0xybNeUHSMBTJ5ZNAcX
somveEfhNyQHyLIG5WWkQ6yKm9eZ8Js1cLEEUoK1Pens9+RNAoIBAQDBCZNUoyL4
Pgvm0N8M5vvos0/iK9mK6dQ+PyK9ulLwQ914lYFnsS4/5Bm3lMKhk7l75uOfCICS
xD5qj8adpCSzTi0FYZn5+v2YJV2dcq85LbS0X1C2tC0x/h+CKHeTAWedaHbolweR
iYJ8LUAh/OO0YDG4Y8NuNKYuu3GMfRtgaZ3ozwC9RrF3Stg4Mvz7mZ2YvIt9KAh4
1G4zffXouksMUR3Ef0m435Q0GFZxbwG9d0S9xhKN9Z6y5m0AXv6JP0cRf5P2hDor
cj+RU5Lt1jOKpEa4JEklHyjkMLzGvilCnZcp3CCtgaxnVkPaxAQE1SzbImsCiuT6
0ZeLk7rLVXhtAoIBAEpXVlF5Xp7BLPUQ2MZlW4ehfYFRStgynndj/yBdkR3j8Bae
v5A+gfLDSFZVZI/91qaZ2QOxBJWX+VXJ6F+Ax1BCGVIPLqDtmH4P3R9tcTdgpty0
Py26IAuaYqNPRPioVRwZgmt/H7a1BwWPsz2695oSNAVoZrWtgoXWuGzncqnI/gVD
K/VygD7FNOZlfslvCfj8Tv7DiYBRty1pVlz0SkkfB3ZDJJ0lHXS1bHAfQtaXNRhT
wXYYa+9F+R5cGOuVANk30yBmb9MLtL2jCJCtA+vmuvAu04mNLOjSscPgKjvP7Fg2
pGigzOgF3M+iJ3iyKD3RWYwzAmJONPWhIJz9KW0CggEBALlw53YRWhC8GlbcJMqS
Q0GisIUHtu55/wjlQgydp/tkVqf2h+ADF/kMuZ/garEp5rAeeGBYnJthpsxb3mOm
QhN2cE2RG4hIE8JLcwlEGQyG2efFARbjM9+ozsAM/AHfAZj3t/Ns0zp+rTl5hvif
pmerWVhXjnCaZ2LRcx2ROfF+xNHXulAaT3XYEqq6YMmbIwiNaDsNcEYTXOJeiRPP
kzT73+ralQnizs7U6oYCK9vFbeYZF84EPTaDogcPOtrCTRWER7I0CGWgVWzYqneM
pOr1MXLIePQOYQwFvfP2zlBOb98otsO3pNWIy5qnX2z9FSBWihJhN+Oz4S+W9YVM
UGkCggEAJrHCoLJC0BzQv169vujovOH65jSndngxN/KhDQPTElmKUz7XcUh68yiR
qWbYtNzcpuc0ocV0P2To2tFaUWhGDghjel+8uJG+OUSegkPRXSRyLOtEwx9+FLpw
aNlB3Yi80Lprm/s0crQ8f+zm/gV1LXqGhuflo/lnygMdgUU1RBvrZvohMVY87eck
07ib4myXmoG/U5Lf+Lvk399NySyy3equoboHu4Izci34CHnfKGZA8nHMUNDqYqGI
RP0xpZzlp0QZRgpOQOt2xXPsAO3h5nOPlYJa7Tb92i4lQEartEcDpZJPgC+Gr9Kt
9Q5v1aEquucco2QmPFOQPhHZaCJArQ==
-----END PRIVATE KEY-----
"""
tls_cert = """
-----BEGIN CERTIFICATE-----
MIIFazCCA1OgAwIBAgIULRrJkdzV+cTqUpqdYYsFolVIJ2EwDQYJKoZIhvcNAQEL
BQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM
GEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAeFw0yMzAyMTcxMDUyMDlaFw0yODAy
MTYxMDUyMDlaMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEw
HwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwggIiMA0GCSqGSIb3DQEB
AQUAA4ICDwAwggIKAoICAQCeZuT0jXfIbCyIsrXkPaJ6SeqOlJyokAbGL1xcuPyq
FQo2KGzStG2B7vI9EX5vPA8PaNToUSUjC/92T+Y4Swl3cEY70F8Lw6toY2eA1m01
sxgeSOyFDXzgmhdr7su+cVgLrBGh8Dus8BYosMcx6ytahFJmD7MjjeRbDhERi6Wl
C5N4KqFcPKh7kd+u0X3WmbQj/Ge+mSh2xJJBuXofMKhFBVZTyAa4Vc4pkoVqj2nC
MgBGYsDkoW48flbzFTURvB6j9MCY8X338GL8Q1o0wvB0ghEL+VZ5SlGa56VJ/1yE
ZSIQkbzXsTNP19RNjwA+rKvYWG7pLaNgwVd35KdNYa9lkrud0JdSZiTXpRU+shQZ
LzZQng0+ArK85L2co45mJImPChLloMZ14tfJlPag2yrlaHcVpWLxgBJCSqaJnDde
sBZ88YIYaS0iMfEHxeJKDBlhwCGB5k21RgdRWDWrvxWDJ+bAUuDjNN4XWix02gNh
hRCWcDAiTY2HTmvOuRRze6f8yBkXxIA5YT8QxQM0SVUL+Wi5Sp/rIZdRiDSyHN3w
519kPd9gcf/OD6/m5GeZiwPvA6RCPc3gpNfbNSlF0qmOm+BtP6s8oBmYV2HtIyry
L0O0VaVTAWGxwAfZo82nGcZ7DCg3ov29HQFRO0UDrbJCYWTzjddfaNSOyFr39SFM
yQIDAQABo1MwUTAdBgNVHQ4EFgQU2yd0UFYG6B+4d2hFm5VdxY+UvfkwHwYDVR0j
BBgwFoAU2yd0UFYG6B+4d2hFm5VdxY+UvfkwDwYDVR0TAQH/BAUwAwEB/zANBgkq
hkiG9w0BAQsFAAOCAgEAYdqK8lw5WwLWp3y0KIlR96WRaS5PxVxu6IljBOjFkMyo
mck3S2jpIWyP++D5njjPyvJ5Q9bfRni6mQcTXHbW3++NKDhDewpRMUpzMoR+0qYL
Q5/WvM/BcMf1zxMKawOAK7H4cNqA/DA9anZrF9Q607Fg8lhjF8V+/hvAM4xbEYKu
98JkTiYiWivJi36NgruF02RrpukD1xyOUpFwuzV31n7sTPikZcOKh3GJ43Ce7jtU
R6B11XyQKIkE3XDSBT61MQXV3x8CntYSchczOAmp+Oj+AxNA5XiZ0oc8oZvC9I7l
1rsA2szO21wQ5g78/hGKcPtNDfD9SBH7OTrsqyUzxmNVN/Tm4mrSPtThn5uf5T4h
ZNYEVhEyhfdQD7mmzurv9+w/f0VjwpN72/uqnS0XaRZNA86LYqwixo3W2R2Hu0f7
jyKjqs2Z2r8hOa6NwM1RikuEuO0Id5ph/XHV8Pd6nwLHD36RZBgHJHo9Lp6DPOcS
+ZYdnEwcDCscOfr6Ec4GGw+I1C8q6ycFTMq66dHv1Bc8VSdacGHluBj10t6pSSxO
dCIt7ke/LD5PS3uzBkeMdEfPCN2EiU4Vc6/BIh3lj8GbmX9zU+/x34DvPhUsUUVi
kBAtL3ogKBt46B88cy8+bfBkZkMcURvotE+rOw4/eZQX07SbQQHksK3tlCyeHrQ=
-----END CERTIFICATE-----
"""
